---
- name: Install required packages
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      tags: setup_lib

    - name: Install fail2ban
      apt:
        name: fail2ban
        state: present
      tags: setup_lib
      ignore_errors: yes

    - name: Ensure fail2ban is started and enabled
      service:
        name: fail2ban
        state: started
        enabled: yes
      tags: setup_lib
      ignore_errors: yes

    - name: Install development tools and libraries
      apt:
        name:
          - libsasl2-dev
          - build-essential
          - libssl-dev
          - libudev-dev
          - pkg-config
          - zlib1g-dev
          - llvm
          - clang
          - cmake
          - make
          - curl
          - wget
          - libprotobuf-dev
          - protobuf-compiler
          - aria2
        state: present
      tags: setup_lib
      ignore_errors: yes
