---
- name: Switch On Identity
  hosts: "{{ on_host }}"
  become: true
  become_user: solv
  gather_facts: no
  vars:
    key_name: "{{ hostvars[inventory_hostname].identity_account }}.json"
    local_key_path: "~/.slv/keys/{{ key_name }}"
  tasks:
    - name: Upload Tower File
      ansible.builtin.copy:
        src: ~/.slv/tower/tower-1_9-{{ hostvars[inventory_hostname].identity_account }}.bin
        dest: /mnt/ledger/tower-1_9-{{ hostvars[inventory_hostname].identity_account }}.bin

    - name: Read local validator key file securely (base64)
      become: false
      delegate_to: localhost
      slurp:
        src: "{{ local_key_path }}"
      register: key_file

    - name: Stop if key file not found
      fail:
        msg: "Key file not found: {{ local_key_path }}"
      when: key_file is not defined

    - name: Set Identity to Validator Key via stdin
      shell: . ~/.profile && agave-validator -l /mnt/ledger set-identity
      args:
        stdin: "{{ key_file.content | b64decode }}"
        executable: /bin/bash
      register: set_identity_result
      timeout: 20
      when: validator_type == 'agave'

    - name: Set Identity to Active Validator Key
      shell: |
        . ~/.profile
        sudo fdctl set-identity --config /home/solv/firedancer-config.toml /home/solv/testnet-validator-keypair.json
      args:
        executable: /bin/bash
      when: validator_type == 'firedancer'

    - name: Add Authorized Voter via stdin
      shell: . ~/.profile && agave-validator -l /mnt/ledger authorized-voter add
      args:
        stdin: "{{ key_file.content | b64decode }}"
        executable: /bin/bash
      ignore_errors: yes
      when: validator_type == 'agave'

    - name: Add Authorized Voter
      shell: . ~/.profile && agave-validator -l /mnt/ledger authorized-voter add /home/solv/testnet-validator-keypair.json
      args:
        executable: /bin/bash
      ignore_errors: yes
      when: validator_type == 'firedancer'
