---
- name: Configure hugetlbfs for hugepages
  hosts: all
  become: true
  tasks:
    - name: Configure 2MB hugepages
      shell: |
        echo "109" | tee /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Configure 1GB hugepages
      shell: |
        echo "29" | tee /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Create /mnt/.huge directory
      file:
        path: /mnt/.huge
        state: directory
        mode: "0755"

    - name: Mount hugetlbfs for 2MB pages
      shell: mount -t hugetlbfs none /mnt/.huge -o pagesize=2097152,min_size=228589568
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Create /mnt/.gigantic directory
      file:
        path: /mnt/.gigantic
        state: directory
        mode: "0755"

    - name: Mount hugetlbfs for 1GB pages
      shell: mount -t hugetlbfs none /mnt/.gigantic -o pagesize=1073741824,min_size=31138512896
      args:
        executable: /bin/bash
      ignore_errors: yes
