---
- name: Switch Off Identity
  hosts: "{{ off_host }}"
  become: true
  become_user: solv
  gather_facts: no
  tasks:
    - name: Wait for Restart Window
      shell: |
        . ~/.profile
        agave-validator -l /mnt/ledger wait-for-restart-window --min-idle-time 2 --skip-new-snapshot-check
      args:
        executable: /bin/bash

    - name: Set Identity to Unstaked Key
      shell: |
        . ~/.profile
        agave-validator -l /mnt/ledger set-identity /home/solv/unstaked-identity.json
      args:
        executable: /bin/bash

    - name: Make sure the ~/.slv/tower directory exists
      shell: mkdir -p ~/.slv/tower
      ignore_errors: yes

    - name: Download Tower File - Make Sure it overwrites the existing file if it exists at the destination
      ansible.builtin.fetch:
        src: /mnt/ledger/tower-1_9-{{ hostvars[inventory_hostname].identity_account }}.bin
        dest: ~/.slv/tower/tower-1_9-{{ hostvars[inventory_hostname].identity_account }}.bin
        flat: yes
