---
- name: Load validator type from inventory
  hosts: all
  gather_facts: no
  tasks:
    - name: Set validator type fact for each host
      set_fact:
        validator_type: "{{ validator_type | default('firedancer') }}"
    
    - name: Debug validator type. Stop if not set
      debug:
        msg: "Validator type is {{ validator_type }}"

    - name: Fail if validator type is not set
      fail:
        msg: "Validator type is not set. Please set it in the inventory."
      when: validator_type is not defined

# 共通処理
- import_playbook: copy_restart_sh.yml
  when: validator_type in ['jito', 'firedancer']

- import_playbook: copy_keys.yml
  when: validator_type in ['firedancer']

- import_playbook: ../cmn/add_solv.yml
  when: validator_type in ['jito', 'firedancer']

- import_playbook: ../cmn/install_package.yml
  when: validator_type in ['jito', 'firedancer']

- import_playbook: ../cmn/update_ubuntu.yml
  when: validator_type in ['jito', 'firedancer']

- import_playbook: ../cmn/install_rust.yml
  when: validator_type == 'firedancer'  # Jito uses separate install_rust

- import_playbook: install_rust.yml
  when: validator_type == 'jito'

- import_playbook: install_jito.yml
  when: validator_type in ['jito', 'firedancer']

- import_playbook: setup_fb_ufw.yml
  when: validator_type in ['firedancer']

- import_playbook: setup_ufw.yml
  when: validator_type in ['jito']

- import_playbook: fail2ban_solana_rate_limit.yml
  when: validator_type in ['jito', 'firedancer']

- import_playbook: ../cmn/mount_disks.yml
  when: validator_type in ['jito', 'firedancer']

- import_playbook: ../cmn/optimize_system.yml
  when: validator_type in ['jito', 'firedancer']

- import_playbook: ../cmn/setup_norestart.yml
  when: validator_type in ['jito', 'firedancer']

- import_playbook: configure_hugetlbfs.yml
  when: validator_type in ['jito', 'firedancer']

- import_playbook: setup_logrotate.yml
  when: validator_type in ['jito', 'firedancer']

- import_playbook: ../cmn/setup_unstaked_identity.yml
  when: validator_type in ['jito', 'firedancer']

- import_playbook: create_overrides.yml
  when: validator_type in ['jito', 'firedancer']

- import_playbook: deploy-start-validator-sh.yml
  when: validator_type == 'jito'

- import_playbook: setup_solv_service.yml
  when: validator_type == 'jito'

- import_playbook: setup_firedancer.yml
  when: validator_type == 'firedancer'

- import_playbook: wget_snapshot.yml
  when: validator_type in ['jito', 'firedancer']
  ignore_errors: yes

- import_playbook: start-solv-service.yml
  when: validator_type == 'jito'

- import_playbook: start_firedancer.yml
  when: validator_type == 'firedancer'
