---
- name: Setup Firedancer
  hosts: all
  become: yes
  become_user: solv
  vars:
    target_file: /home/solv/firedancer/src/app/fdctl/run/run_agave.c
    search_key: "config->development.gossip.allow_private_address"
    add_line: 'ADD( "--staked-nodes-overrides", "/home/solv/overrides.yml" );'
  vars_files:
    - ~/.slv/versions.yml
  tasks:
    - name: Clone Firedancer repository
      git:
        repo: https://github.com/firedancer-io/firedancer.git
        dest: /home/solv/firedancer
        update: yes
        force: yes
        version: v{{ mainnet_validators.version_firedancer }}

    - name: Initialize git submodules
      command: git submodule update --init --recursive
      args:
        chdir: /home/solv/firedancer

    - name: Generate overrides.yml from template
      template:
        src: ~/.slv/mainnet-validator/overrides.yml.j2
        dest: /home/solv/overrides.yml
        mode: "0755"
        owner: solv
        group: solv
      vars:
        staked_rpc_identity_account: "{{ hostvars[inventory_hostname].staked_rpc_identity_account }}"
        staked_rpc_amount: "{{ hostvars[inventory_hostname].staked_rpc_amount }}"
      ignore_errors: yes

    - name: Check if line already exists
      shell: |
        grep -F "$(printf %s '{{ add_line }}')" "{{ target_file }}" && echo "FOUND" || echo "NOT_FOUND"
      register: grep_result

    - name: Debug grep_result
      debug:
        var: grep_result.stdout_lines

    - name: Insert line 3 lines after search_key if not exists
      shell: |
        line_num=$(grep -n '{{ search_key }}' '{{ target_file }}' | head -n1 | cut -d':' -f1)
        insert_line=$((line_num + 3))
        sed -i "${insert_line}i $(printf %s '{{ add_line }}')" "{{ target_file }}"
      when: "'FOUND' not in grep_result.stdout_lines"

    - name: Run deps.sh script with yes (async/poll)
      shell: |
        yes y | ./deps.sh
      args:
        chdir: /home/solv/firedancer
      async: 300 # wait for 5 minutes
      poll: 15 # check every 15 seconds
      register: deps_result
      until: deps_result.rc == 0
      retries: 3
      delay: 10

    - name: Build Firedancer with make
      shell: |
        export PATH="$HOME/.cargo/bin:$PATH"
        . $HOME/.cargo/env
        make -j fdctl solana
      args:
        chdir: /home/solv/firedancer
        executable: /bin/bash
      register: build_result
      until: build_result.rc == 0
      retries: 3
      delay: 10

    - name: Create symbolic link for fdctl
      file:
        src: /home/solv/firedancer/build/native/gcc/bin/fdctl
        dest: /usr/local/bin/fdctl
        state: link
      become: yes
      become_user: root

    - name: Create config.toml
      template:
        src: ~/.slv/mainnet-validator/firedancer-config.toml.j2
        dest: /home/solv/firedancer-config.toml
        owner: solv
        group: solv
        mode: "0644"
      vars:
        block_engine_region: "{{ hostvars[inventory_hostname].block_engine_region }}"
        vote_account: "{{ hostvars[inventory_hostname].vote_account }}"
        commission_bps: "{{ hostvars[inventory_hostname].commission_bps }}"

    - name: Create Firedancer systemd service file with template
      template:
        src: ~/.slv/mainnet-validator/firedancer.service.j2
        dest: /etc/systemd/system/firedancer.service
        owner: root
        group: root
        mode: "0644"
        force: yes
      become: yes
      become_user: root
      register: firedancer_service
      notify: Reload systemd daemon

    - name: Enable Firedancer
      systemd:
        name: firedancer
        enabled: yes
      become: yes
      become_user: root

    - name: Ensure /mnt directory has correct permissions
      shell: sudo chown -R solv:solv /mnt && sudo chmod -R 700 /mnt

  handlers:
    - name: Reload systemd daemon
      command: systemctl daemon-reload
      become: yes
      become_user: root
