---
- name: Load validator type from inventory
  hosts: all
  gather_facts: no
  tasks:
    - name: Set validator type fact for each host
      set_fact:
        validator_type: "{{ validator_type | default('agave') }}"
    
    - name: Debug validator type. Stop if not set
      debug:
        msg: "Validator type is {{ validator_type }}"

    - name: Fail if validator type is not set
      fail:
        msg: "Validator type is not set. Please set it in the inventory."
      when: validator_type is not defined

- import_playbook: stop_solv.yml
  when: validator_type == 'agave'

- import_playbook: stop_firedancer.yml
  when: validator_type == 'firedancer'

