---
- name: Fix permissions for system commands
  hosts: all
  become: true
  tasks:
    - name: Fix permissions for common system commands
      file:
        path: "{{ item }}"
        mode: "0755"
        state: file
      with_items:
        - /usr/bin/systemctl
        - /bin/systemctl
        - /usr/bin/curl
        - /usr/bin/wget
        - /bin/curl
        - /bin/wget
        - /usr/bin/gcc
      ignore_errors: yes

    - name: Fix permissions for directories
      file:
        path: "{{ item }}"
        mode: "0755"
        state: directory
      with_items:
        - /usr/bin
        - /bin
        - /usr/local/bin
      ignore_errors: yes
